from backend.db_config import (
    DB_CONNECTION_STRING,
    DB_CONNECTION_STRING_CML,
    DB_CONNECTION_STRING_WS,
)

CHMI_IMG_API = "http://192.168.64.196:5001"
TELCOSENSE_IMG_API = "http://192.168.64.154:5001"


class Config:
    SQLALCHEMY_DATABASE_URI = DB_CONNECTION_STRING
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    JWT_SECRET_KEY = "jwt_secret_key"
    JWT_TOKEN_LOCATION = "cookies"
    JWT_COOKIE_SECURE = False
    SQLALCHEMY_BINDS = {"ws": DB_CONNECTION_STRING_WS, "cml": DB_CONNECTION_STRING_CML}
